name: ESLint action, typecheck and build

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.16
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      # Installs pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Installs all the packages
      - name: Install dependencies and packages
        run: pnpm install

        # Generate prisma client
      - name: Generate prisma client
        run: pnpm generate

      # Runs the lint script
      - name: Run the lint Script
        run: pnpm lint

      # Runs the typecheck script
      - name: Run the typecheck Script
        run: pnpm generate && pnpm typecheck

      # Runs the build script
      - name: Run the build Script
        run: pnpm build
